### ISSUE TITLE
Round Rectangle vs. Rectangle

### ISSUE THREAD

**Issue by omidb** [andreaferretti/paths-scala-js#3]
Hi, why Round Rectangle and Rectangle get different inputs? and I belive Round Rectangle is not working properly!

**Comment by andreaferretti** [comment]
It is actually called `CurvedRectangle`, and it is not meant to be a rectangle with rounded corners (though that would be a nice addition), but actually a rectangle whose horizontal sides look curvy. Too see it, have a look at the [Sankey diagram here](http://andreaferretti.github.io/paths-js-demo/).

It has more parameters than a rectangle because it is less constrained. It is easy to see that a rectangle is defined by 4 parameters, but a curved rectangle needs 6.
