### ISSUE TITLE
Legend for StockChart

### ISSUE THREAD

**Issue by sadbuttrue1** [andreaferretti/paths-scala-js#5]
Hi,
Is it possible to add legend feature?

Thanks!

**Comment by andreaferretti** [comment]
Hi, @sadbuttrue1. I think this does not fall into the scope of the library.

I suggest that you read the [Paths.js README](https://github.com/andreaferretti/paths-js) and possibly follow some links to the blog posts for the idea behind paths.js. In short, the very reason why the library exists is to provide a way to generate shapes from data _without_ taking care of the actual rendering.

This means that all the higher level logic, such as interactions, styling, legends and so on is demanded to clients. Think of Paths.js as a building block upon which to build widgets.

Since Paths.js is not directly responsible to draw anything to the screen, it is quite difficult to make it generate a legend. In particular, a legend means writing text, and Paths is not aware of text at all.

I have done examples that feature legends - essentially you have to iterate over your dataset and draw a square and a text for each item. This is pretty orthogonal to the path generation part, and is best left to the view rendering code.

**Comment by sadbuttrue1** [comment]
Sorry, can you link «I have done examples that feature legends»? I don't see it…

**Comment by andreaferretti** [comment]
You are right that these are not in the published examples - it was for internal use. I will see if I am able to separate only that part from the widget that was using it and make it public

**Comment by sadbuttrue1** [comment]
Thank you!

**Comment by andreaferretti** [comment]
Ok, I have added a simple example [here](http://andreaferretti.github.io/paths-js-react-demo/) - source [here](https://github.com/andreaferretti/paths-js-react-demo/blob/master/js/components/drawing.jsx)

It is for the parent library (it was just quicker), but the same can be done mutanda mutandis with paths-scala-js

**Comment by sadbuttrue1** [comment]
Cool, thanks!
Sorry for the audacity, but do you have example with axes with scale?

**Comment by andreaferretti** [comment]
What one needs to do is the following. The chart returns both a horizontal and a vertical scale. Say you want to draw the y-axis. This starts, say at 0 (assuming the data is positive), and ends at maximum-of-your-data.

Hence you can call `yscale(0)` and `yscale(maximum-of-your-data)` to get the two extreme points. The x coordinate of such points is `xscale(minimum-of-your-times)`. You can then draw a [line](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line) between two such points.

An example is [the third chart here](http://andreaferretti.github.io/paths-js-react-demo/), source [here](https://github.com/andreaferretti/paths-js-react-demo/blob/master/js/charts/timeline.jsx#L147-L148)

**Comment by sadbuttrue1** [comment]
Is it possible to add scale? I mean marks with numbers on axis. Like [here](http://www.labri.fr/perso/nrougier/teaching/matplotlib/figures/exercice_1.png) -4 -3 -2 -1 0 and so on on x axis.

**Comment by andreaferretti** [comment]
Yes. Just call, say, `xscale(-3)` and `yscale(0)` to know the coordinates of where to put the `-3` annotation. Then you can put a little circle or a little line segment to mark the point, and a the text, translated a few pixels below so that it does not touch the axis. I leave the details to you :-)
